services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - api
    networks:
      - fptalumni-network
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fptalumni-network
    entrypoint: sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; docker kill -s HUP nginx; done"

  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - fptalumni-network

  # One-time DB init script runner
  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./scripts:/scripts
    entrypoint: >
      bash -c "
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -i /scripts/database.sql
      "
    networks:
      - fptalumni-network

  # FPT Alumni Connect API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SQLServerDatabase=Server=sqlserver;Database=AlumniConnect;User ID=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    depends_on:
      - db-init
    networks:
      - fptalumni-network
    restart: unless-stopped

volumes:
  sqlserver_data:


networks:
  fptalumni-network:
    driver: bridge